forms/s2021_EveRunNumber
=> Add embryo indentifier to input file

code/startup/MokaStartup.pyw, modules/Firefox
=> Windows 10 updates

forms/2022_EveManual
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/353)
=> capture and incorporate scan number in the filename fix #351 #352

forms/2022_EveManual
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/356)
=> add many more comments to eve form

forms/87014 ExomeGenePanel
Fixes #404
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/405)
=> Quickfix for v3.80 - Change separator

code/startup/MokaStartup.pyw
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/398)
=> Open Access in runtime mode. Fixes #397

forms/2001 MokaImport, modules/Firefox
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/417)
=> V3.80 win10 bugfixes

forms/6001 DNAextractionlist, forms/6002 PrintSendawayLabels, forms/x905 LabelPrinting
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/423)
=> Update label printer for Admin forms

code/startup/MokaStartup.pyw
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/428)
=> Rolling back startup script because runtime causes problems

forms/s03_GWFISHReports
Fixes #424
Save on H drive to avoid permissions issues
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/429)
=> Change location where Word doc is saved

forms/s0901_NGSVariants, forms/s0901_WESTestResults
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/433)
=> Acmg classification - couple of bug fixes

code/VCFImport/VCFImport.py, forms/s0901_NGSCurrentVar, forms/s0901_NGSPrevVars, forms/s0901_NGSVariants
Reduced the number of required fields, which allows it to be used for Ingenuity verification using a minimal VCF.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/434)
=> VCFImport: Reduced the number of required fields. Also bug fix for acmg form.

code/hyb_qc_import/hyb_qc_import.py, forms/924 CheckHybDetails, forms/924 CheckHybDetails_SQL
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/438)
=> Added script to automate importing of array QC data

code/hyb_qc_import/hyb_qc_import.py, forms/924 CheckHybDetails
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/441)
=> Updated script so fe_files don't need to be moved to subfolders

forms/87010 ExomePatient_CustomMsgBox, forms/87010 ExomePatients, forms/87016_Exome_Internal_ApprovalForm, forms/87017 Exome_External_ApprovalForm, forms/s87018_ExomeStatusPopup
any other changes were already in production but not committed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/444)
=> Updated email address. Fixes #443.

forms/s0901_WESTestResults
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/449)
=> allow the status to be changed to testfailed

forms/s0901_WESTestResults
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/450)
=> change the patient status to complete when test status is test failed.

forms/s0901_WESTestResults
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/452)
=> change name of the coverage report

forms/4752 DeletePatientRecords
Restrict access to the Danger Danger page to array duty scientists. Fixes #432 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/454)
=> Restrict access to approved personnel only.

forms/9303 MyPGDAnalyses_SQL
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/458)
=> Create 9303 MyPGDAnalyses_SQL

forms/88005_GEL_InsertPatient
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/463)
=> correct query

forms/s88005_GEL_updateNGSTest
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/465)
=> requery subform. fix #464

forms/88005_GEL_InsertPatient
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/468)
=> add referral id to  subform record source

forms/s0901_NGSCoveragePopup
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/480)
=> change the argument used for tertiary panel

forms/4010 RefSeqGenes, forms/4713 UCSCGenomeBrowser, forms/s0141_OligoPreliminaryResults, forms/s09_OligoPreliminaryResults, forms/s09_Previous, forms/s09_PreviousByChrLookup, forms/s9604_Calls
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/483)
=> Update UCSC links to devdisorders browser sessions

forms/s09_ArrayTest
My changes relate to command83 and command96.  It looks like some minor formatting changes in the current version of Moka have not been version controlled in Github.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/478)
=> Split PGD print function fixes #145

code/VCFImport/VCFImport.py, forms/s0901_WESTestResults, forms/s0902_OncologyTestResults
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/481)
=> manually select the VCF files to import variants from

forms/88005_GEL_InsertPatient SQL
fixes #488
Add wildcard to PRU and move where clause to TrustPatientID
Remove DISTINCT as this is not necessary
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/489)
=> Allow full or partial PRU

forms/0901 ExomeNGSResults, forms/s0901_NGSVariants_SQL, forms/s0901_WESTestResults
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/501)
=> WES improvements

forms/02502 DaybookTestsToAuthorise, forms/02503 DaybookTestsEdit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/503)
=> Remove US findings tick box

forms/88005_GEL_InsertPatient, forms/s88005_GEL_updateNGSTest
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/504)
=> 100 k booking in

forms/4739 GitHubIssues
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/516)
=> GitHub link update

tables/NGSVariant
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/523)
=> NGSVariant change nvarchar(50) to nvarchar(max)

forms/473 Meeting Room booking
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/526)
=> Create 473 Meeting Room booking

queries/s_WESReportedGenes
Updated to include all fields included in template submitted to UKAS.
Only inlcude variants added after 11/01/2018 (when the ACMG form was added)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/527)
=> Updated WES gene list query for UKAS

forms/987 ArrayAnalyses, forms/989 ArrayAnalysisChecks
These are old forms that were already in live Moka but not previously in GitHub.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/528)
=> Original forms for array analysis and checking totals prior to update

forms/987 ArrayAnalyses, forms/989 ArrayAnalysisChecks, forms/s987_ArrayAnalyses_SQL, forms/s989_ArrayAnalysisChecks_SQL
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/529)
=> Updates to competency records to address https://github.com/moka-guys/helpdesk/issues/236

forms/521 ClincianAccess
fixes moka-guys/helpdesk#255
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/530)
=> 180831 update USCC track links in Moka clinic

forms/987 ArrayAnalyses, forms/989 ArrayAnalysisChecks
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/531)
=> Fix date issues in new array figures forms

forms/9225 LabellinDetails_SQL, forms/9225 LabellingDetails, forms/92252 AssignLabelledDNAsToHyb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/536)
=> Add current production code not previously in GitHub

forms/9225 LabellingDetails
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/538)
=> Update 9225 LabellingDetails

forms/87010 ExomePatients, forms/87014 ExomeGenePanel, modules/Firefox
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/540)
=> Escape apostrophes in names

forms/s01_GeneworksDNA_SQL, views/gwv-dnanumberlinked, views/gwv-dnaspecimenlinked
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/545)
=> Refreshed query to use moka views

forms/02510 DaybookPCRs
as requested.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/547)
=> Remove autostatus function

forms/s87026_OncologyNGSPopup
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/549)
=> capture the version of pipeline used for oncology samples

tables/GeL_Probands, tables/Probands_100k
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/548)
=> New table to link GeL participant IDs to Geneworks

tables/VariantSub
Fixes #552
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/553)
=> Create VariantSub table

forms/88009_GEL_neg_neg_list, forms/s88005_GEL_updateNGSTest, forms/s88005_GEL_updateNGSTest_SQL, forms/s88009_GEL_negneg_list_SQL, tables/NGStest
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/554)
=> Update Moka for negneg reporting

forms/47381 VariantIntMinutes, forms/47382 VariantIntAddAgenda, forms/47383 DevDisProjectMinutes, forms/47384 DevDisProjectsAddAgenda
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/559)
=> New smartsheet links

forms/s0901_NGSVariants_SQL
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/560)
=> Add b38 chromosome

forms/s0901_NGSVariantsEditable, forms/s0901_NGSVariants_SQL, modules/binfx_tools
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/567)
=> V1.110a bugfix

forms/87018 ExomeStatus, forms/87020 ExomeLab
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/568)
=> New wes referral i ds

forms/989 ArrayAnalysisChecks, forms/s989_ArrayAnalysisChecks_SQL
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/572)
=> 989 add checker

forms/985 BookingInCount SQL
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/571)
=> Change staff shown on array booking in chart

forms/s02_NGSTest
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/574)
=> requesteddate->daterequested

forms/0901 ExomeNGSResults, forms/s0901_WESTestResults
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/577)
=> 100k neg button

forms/989 ArrayAnalysisChecks
Fixes #579
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/580)
=> Add CJB to ArrayAnalysisChecks

code/VCFImport/VCFImport.py, code/VCFImport/example_config.ini, code/hyb_qc_import/example_config.ini, code/hyb_qc_import/hyb_qc_import.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/583)
=> Pull server details from config file

forms/02510 DaybookPCRs, forms/s0901_WESTestResults
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/585)
=> Natasha updates oct19

forms/09 ArrayResultsByPosition
Bugfix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/588)
=> Force refresh of hyb ID field

forms/1109 Analyse_SQL, forms/1110 Check_SQL
Show additional statuses on forms 1109 & 1110.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/589)
=> V3.116b bugfix

forms/0901 ExomeNGSResults, forms/s0901_WESTestResults
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/591)
=> Edit ngs check date

forms/s09_ArrayTest
Good thing I just commented out the code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/592)
=> Added in that function that I predicted people would end up asking for

forms/1117 ReportEmailNotSent, forms/1117 ReportEmailNotSent_SQL, forms/s09_ArrayTest
- Create a list of array tests where send report email button has not been clicked (for approriate referral types)
- Add PRU to report email subject
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/593)
=> Paperless arrays the revenge

forms/s09_ArrayTest, forms/s09_ArrayTest SQL
Also, add priority to body of email.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/woook/moka-fe/594)
=> Addedd referral organisation to email

forms/472 Barista, forms/4733 BaristaInterpretation, forms/s0901_NGSVariantACMGPopup
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/597)
=> V3.119 Updates to ACMG form, Array Result Code Field and Moka Barista Links

forms/s09_ArrayTest
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/598)
=> Prevent status being set to complete without report being sent

forms/s0901_NGSVariants, tables/NGSVariant
Update patientlog and ngslogmemo after variant is triaged by a clinician
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/599)
=> update logs after triaging variant

forms/0 StartPage, forms/0901 ExomeNGSResults, forms/88001_find_100k_case_SQL, forms/s0901_NGSVariants, forms/s88001_find_100k_case, forms/s88001_find_100k_case_SQL
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/601)
=> Clinician variant view

forms/0901 ExomeNGSResults, forms/s0901_NGSVariantsAnnotations
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/602)
=> Clinician  variant view minor update

forms/s09_ArrayTest
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/603)
=> Open in print preview, so that user can change print settings

forms/s09_ArrayTest
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/604)
=> Change PGD results sheet to open in print preview mode

forms/9225 LabellingDetails, forms/92252 AssignLabelledDNAsToHyb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/614)
=> Updated staff - include new starters, remove old

forms/87020 ExomeLab
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/618)
=> Update 87020 ExomeLab

forms/88012 GeL_case_list_filter
Awaiting 1st check, 2nd check, report button now filters cases where status is not set to complete, test failed and not required
Awaiting authorisation button now filters cases where status is authorisation
All negnegs are also filtered out
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/619)
=> Gel filter buttons filter 'completed' cases

tables/Status
[GMSstatus] [tinyint] NULL,
[SortingGMSstatus] [tinyint] NULL,
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/620)
=> Added two columns to status table

forms/4736 Phenotips, forms/87012 ExomeTest, forms/s0901_WESTestResults, forms/s0902_OncologyTestResults
Phenotips Migration - Updated hard-coded phenotips references in MOKA.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/621)
=> Phenotips migration

forms/02510 DaybookPCRs, forms/02511 DaybookPCRsAll
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/623)
=> Fix pcr status issue

forms/02510 DaybookPCRs, forms/02511 DaybookPCRsAll
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/624)
=> change message box

forms/s0901_NGSVariantACMGPopup
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/625)
=> Open WES ACMG guide in browser when users click WES guidance label box

forms/87010 ExomePatients
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/626)
=> Update 87010 ExomePatients - Fix incorrect PanelType value for new user-defined WES panels

forms/989 ArrayAnalysisChecks, forms/s989_ArrayAnalysisChecks_SQL
Note: Code review is only for array forms as WES variants tab (s0901_WESTestResults) is a change to the form design only
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/637)
=> V3.132 Add users to array checking chart and shift WES variants tab

forms/s0901_WESTestResults
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/641)
=> Add "other" result code

forms/9302 MyAuthorised_SQL, forms/989 ArrayAnalysisAuthorised
Add new list in the array menu where users can enter initials and all cases authorised by that user (both as first and second authoriser) will appear in a table (based on '9302 MyChecks').
Add new form (based on '989 ArrayAnalysisChecks') to the array menu to display number of authorised cases (both as first and second authoriser) for a set of users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/642)
=> Array audits

forms/s09_ArrayTest
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/643)
=> update email address

forms/s09_ArrayTest
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/646)
=> array email changed again

forms/9225 LabellingDetails, forms/92252 AssignLabelledDNAsToHyb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/647)
=> Add ASS to array runsheets

forms/990 Ongoing_Tissues_Array_Audit_SQL
- Change the SQL so v_DNALabellingHybPatients table is a LEFT JOIN so that patients without a HybID will be returned as part of this query
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/649)
=> Updating array tissues audits

forms/87020 ExomeLab
- Add optional call to function on loading to improve form loading speed
- Remove unneeded refresh to improve loading speed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/650)
=> Improve speed of WES Dashboard

views/v_ArrayAnalysis.sql.txt, views/v_ArrayStatus.sql.txt, views/v_PatientDetails.sql.txt, views/v_Phenotype.sql.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/653)
=> Views created for use with a read only Moka

forms/s09_OligoPreliminaryResults
Removed a duplicated function created during a merge conflict  of previous changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/657)
=> Remove duplicate function from merge conflict

forms/s09_OligoPreliminaryResults
A duplicate function was erroneously created during a merge conflict.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/658)
=> Removed duplicate function from merge conflict

forms/33 Inventory Consumables, forms/33 Inventory Consumables SQL
Added a field for a URL to contain links to manufacturers websites as per ticket INC0073185
- Updated SQL to pull in field CompanyURL
- Added VBA code so url is opened on double click
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/666)
=> Consumables url

code/automate_array_booking_in/ImportTxtToDBConfig, forms/0202 AutoBookingInArrays, forms/s0202_AutoBookingInArrays_SQL
- Change statusID in python config for auto booking in arrays script
- Change s0202_AutoBookingInArrays_SQL to look for referralID for 'arrays to be booked in'
-  Add VBA code for refresh button to 0202_AutoBookingInArrays
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/673)
=> Auto array status update

forms/989 ArrayAnalysisAuthorised
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/674)
=> Add more authorisers

forms/s0202_AutoBookingInArrays_SQL
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/678)
=> update referral ID

reports/FamilyResults_Auto_PGD_Report
Add standard comment to PGD report
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/638)
=> first commit

forms/02510 DaybookPCRs, forms/02511 DaybookPCRsAll
ensures status is changed if msgbox isn't closed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/685)
=> remove msgbox

forms/0901 ExomeNGSResults, forms/s0901_WESTestResults
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moka-guys/moka-fe/687)
=> 0901 exome ngs results 100k
